// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akagxwfipsrypeapvfam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYWd4d2ZpcHNyeXBlYXB2ZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzcwMzksImV4cCI6MjA2NjY1MzAzOX0.Gb8Rl7sO8INOIrcGqlKYR-rSQX4QTXXuyDuN2b5LWIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);